[2022-09-08 11:41:48,429] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example3.t1 manual__2022-09-08T03:30:24.121990+00:00 [queued]>
[2022-09-08 11:41:48,436] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example3.t1 manual__2022-09-08T03:30:24.121990+00:00 [queued]>
[2022-09-08 11:41:48,436] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-08 11:41:48,437] {taskinstance.py:1377} INFO - Starting attempt 4 of 4
[2022-09-08 11:41:48,437] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-08 11:41:48,448] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-09-08 03:30:24.121990+00:00
[2022-09-08 11:41:48,450] {standard_task_runner.py:52} INFO - Started process 13870 to run task
[2022-09-08 11:41:48,456] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example3', 't1', 'manual__2022-09-08T03:30:24.121990+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/example3.py', '--cfg-path', '/var/folders/ll/lb_b4vvx7cgfp2wpfsv4w6zm0000gn/T/tmp5e8_pyod', '--error-file', '/var/folders/ll/lb_b4vvx7cgfp2wpfsv4w6zm0000gn/T/tmpv64a6otx']
[2022-09-08 11:41:48,457] {standard_task_runner.py:80} INFO - Job 37: Subtask t1
[2022-09-08 11:41:48,504] {task_command.py:371} INFO - Running <TaskInstance: example3.t1 manual__2022-09-08T03:30:24.121990+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-09-08 11:41:48,558] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example3
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T03:30:24.121990+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T03:30:24.121990+00:00
[2022-09-08 11:41:48,595] {local_task_job.py:156} INFO - Task exited with return code -11
[2022-09-08 11:41:48,614] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=example3, task_id=t1, execution_date=20220908T033024, start_date=20220908T034148, end_date=20220908T034148
[2022-09-08 11:41:48,645] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
